controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    amr_controller:
      type: diff_drive_controller/DiffDriveController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    # gripper_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


amr_controller:
  ros__parameters:
    type        : diff_drive_controller/DiffDriveController
    use_stamped_vel: false
    publish_rate: 20.0 

    left_wheel_names:
      - "driving_wheel_front_left_joint"
      - "driving_wheel_back_left_joint"
    
    right_wheel_names:
      - "driving_wheel_front_right_joint" 
      - "driving_wheel_back_right_joint"

    wheel_separation : 0.39
    wheel_radius : 0.0825

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.5

    # Base frame_id
    base_frame_id: base_footprint
    odom_frame_id: odom
    # Publish limited velocity
    publish_limited_velocity: true

    # Publish wheel data
    publish_wheel_data: true

    # Publish to TF directly or not
    enable_odom_tf: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 4.0  # m/s
        min_velocity           : -4.0 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.2  # m/s^2
        min_acceleration       : -1.2 # m/s^2
        has_jerk_limits        : false
        # max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 20.0  # rad/s
        min_velocity           : -20.0  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 6.0  # rad/s^2
        min_acceleration       : -6.0   # rad/s^2
        has_jerk_limits        : false
        # max_jerk               : 2.5  # rad/s^3


arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    # controller_frequency: 10