twist_mux:
  ros__parameters:
    topics:
      keyboard: 
        topic   : key_vel
        timeout : 0.5
        priority: 90
      navigation: 
        topic   : cmd_vel
        timeout : 0.5
        priority: 80